blocks-break:
  # This is where you put the names of the blocks that you would like to be logged when they are broken, case insensitive
  # BEDS
  - "WHITE_BED"
  - "ORANGE_BED"
  - "MAGENTA_BED"
  - "LIGHT_BLUE_BED"
  - "YELLOW_BED"
  - "LIME_BED"
  - "PINK_BED"
  - "GRAY_BED"
  - "LIGHT_GRAY_BED"
  - "CYAN_BED"
  - "BLUE_BED"
  - "PURPLE_BED"
  - "GREEN_BED"
  - "BROWN_BED"
  - "RED_BED"
  - "BLACK_BED"
  #DOORS
  - "OAK_DOOR"
  - "BIRCH_DOOR"
  - "SPRUCE_DOOR"
  - "JUNGLE_DOOR"
  - "ACACIA_DOOR"
  - "DARK_OAK_DOOR"
  - "IRON_DOOR"
  - "CHEST"
  - "BARREL"
blocks-placed:
# This is where blocks broken will go

# This is where your discord token goes for discord integration
discordToken: "abcdefghijklmnopqrstuvwxyz123456789"

# This is the prefix used for issuing commands via discord, can not contain spaces,
#   ideally this should be your server name
prefix: "setme"
